site_name: Cocolle
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'Teal'
    accent: 'Red'
extra:
  search:
    language: 'en, ja'
markdown_extensions:
  - mdx_truly_sane_lists
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
